### PR TITLE
Create binaries using pkg

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by kkrieger85** [comment]
@DanielRuf how can I review/test this PR? Is it possible to run GH Actions on branches?

**Comment by kkrieger85** [comment]
I ran this commands with following results:

```
yarn --silent                                      
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

```
yarn add pkg                                         
yarn add v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 102 new dependencies.
```

```
yarn pkg index.js -o website-checks --targets linux,macos,win 
yarn run v1.21.1
$ /home/kkrieger/htdocs/git-contrib/website-checks/node_modules/.bin/pkg index.js -o website-checks --targets linux,macos,win
> pkg@4.4.2
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.17.0-linux-x64   [====================] 100%
  fetched-v10.17.0-macos-x64   [====================] 100%
  fetched-v10.17.0-win-x64     [====================] 100%
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/puppeteer/.local-chromium
  path-to-executable/puppeteer
> Warning Cannot resolve ''./checks/' + check'
  /home/kkrieger/htdocs/git-contrib/website-checks/modules/cli-help.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
Done in 11.92s.
```

```
ls -al 
(only new files)
-rwxr-xr-x   1 kkrieger kkrieger 42283318 Dez 23 11:17 website-checks-linux
-rwxr-xr-x   1 kkrieger kkrieger 43296810 Dez 23 11:17 website-checks-macos
-rw-r--r--   1 kkrieger kkrieger 38566759 Dez 23 11:17 website-checks-win.exe
-rw-r--r--   1 kkrieger kkrieger    60636 Dez 23 11:16 yarn.lock

```

**Comment by kkrieger85** [comment]
```
./website-checks-linux https://kkrieger.de            
website-checks 1.17.0
(node:16524) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/snapshot/website-checks/node_modules/puppeteer/lib/Launcher.js:119:15)
(node:16524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by DanielRuf** [comment]
It seems you have used npm before. The warning regarding the lockfile can be safely ignored.

**Comment by DanielRuf** [comment]
It works only when Chromium / Chrome is globally available. I do not (yet) plan to pack it with the binary. Installing `puppeteer` globally might resolve this.

**Comment by kkrieger85** [comment]
Installed puppeteer globally:

`npm i -g puppeteer`

tried again to check with binary:

```
./website-checks-linux https://kkrieger.de    SIGINT(2) ↵  3490  11:33:26
website-checks 1.17.0
(node:24345) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/snapshot/website-checks/node_modules/puppeteer/lib/Launcher.js:119:15)
(node:24345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Rebuild packages and tried test again: Same error as above

**Comment by DanielRuf** [comment]
Hm, I think it does not work as long as the chromium binary is not in the PATH variable.

I'll try to find a solution when I find some time for this. This PR is just a nice to have and not really needed / required.

**Comment by DanielRuf** [comment]
See https://github.com/zeit/pkg/issues/204 which contains a few solutions.

**Pull request closed without merging**
