### PR TITLE
Enable strict mode - closes #57

### LINKED ISSUE #57: enable strict mode for all files
By adding the line `'use strict';` we should enforce the strict mode to catch possible issues as early as possible.

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by MyIsaak** [comment]
This branch is out of date, therefore the newer files don't have `use strict` labeled above. When the newer files are labeled this PR looks good to me.

**Comment by DanielRuf** [comment]
> This branch is out of date, therefore the newer files don't have `use strict` labeled above. When the newer files are labeled this PR looks good to me.

Feel free to update and work on this branch. I have not really time so far.

**Comment by MyIsaak** [comment]
I will look into it.

**Comment by MyIsaak** [comment]
@DanielRuf this PR has been amended to suit the YellowLab Tools addition. Pending review.

**Comment by DanielRuf** [comment]
> @DanielRuf this PR has been amended to suit the YellowLab Tools addition. Pending review.

Awesome, thank you very much. LGTM.

**Comment by DanielRuf** [comment]
@MyIsaak I think we can merge this, right?

**Comment by MyIsaak** [comment]
Yes @DanielRuf IMO it is ready, however the merging is blocked due to a pending review.

**Comment by DanielRuf** [comment]
> Yes @DanielRuf IMO it is ready, however the merging is blocked due to a pending review.

No problem. I can still merge with admin rights or you do the review and try to merge it =)

**Comment by MyIsaak** [comment]
I wouldn't mind being on the maintainers team. That way I can submit my review. Then you can merge since you are the PR author.

**Comment by DanielRuf** [comment]
> I wouldn't mind being on the maintainers team. That way I can submit my review. Then you can merge since you are the PR author.

Done. You should receive an invitation.

**Review by MyIsaak — APPROVED** [review]

**Pull request merged**
